// react-example/src/skilltree/HelloWorldSkillsDisplay.js
/*
 * Copyright 2020 SkillTree
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
import React from 'react';
import { SkillsDisplay } from '@skilltree/skills-client-react';

const HelloWorldSkillsDisplay = () => {
    return (
        <SkillsDisplay />
    )
};

export default HelloWorldSkillsDisplay;

// vuejs-example/src/components/HelloWorldSkillsDisplay.vue
/*
Copyright 2020 SkillTree

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    https://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
<template>
    <div>
        <skills-display/>
    </div>
</template>

<script>
    import {SkillsDisplay} from '@skilltree/skills-client-vue';

    export default {
        name: "HelloWorldSkillTree",
        components: {SkillsDisplay},
    }
</script>

<style scoped>

</style>
